import { Bootstrap } from '#components/Bootstrap';
import type { Metadata } from 'next';
import { Container } from 'react-bootstrap';

import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.min.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Major Commitments',
  description: 'Generated by create next app'
};

type Slots = Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>;

export default async function RootLayout({ children }: Slots) {
  return (
    <html lang="en">
      <body>
        <Container className="mt-3">{children}</Container>
        <Bootstrap />
      </body>
    </html>
  );
}
